#!/usr/bin/env python

"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.15
 Generation time: Wed Jul 14 18:33:06 2004
   Source file: projectdetail.tmpl
   Source file last modified: Wed Jul 14 18:30:56 2004
"""

__CHEETAH_genTime__ = 'Wed Jul 14 18:33:06 2004'
__CHEETAH_src__ = 'projectdetail.tmpl'
__CHEETAH_version__ = '0.9.15'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFS=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class projectdetail(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''<html>
    <head>
        <title>Project</title>
    </head>
    <body>
        <small><a href="index?view=projectlist">Home</a></small>>
        <small><u>''')
        write(filter(VFS(SL + [globals(), __builtin__],"project.name",True), rawExpr='$project.name')) # from line 7, col 19.
        write(' (')
        write(filter(VFS(SL + [globals(), __builtin__],"project.version",True), rawExpr='$project.version')) # from line 7, col 34.
        write(''')</u></small>        
        <h1>Project files:</h1>
        <hr/>
''')
        for file in VFN(VFS(SL + [globals(), __builtin__],"project",True),"getFiles",False)():
            write('            <p><a href="index?view=filedetail&file=')
            write(filter(VFN(file,"id",True), rawExpr='$file.id')) # from line 11, col 52.
            write('">')
            write(filter(VFN(file,"name",True), rawExpr='$file.name')) # from line 11, col 62.
            write('</a></p>\n')
        write('    </body>\n</html>\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_projectdetail= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    projectdetail().runAsMainProgram()

