#!/usr/bin/env python

"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.15
 Generation time: Tue Jul 20 00:13:27 2004
   Source file: projectlist.tmpl
   Source file last modified: Tue Jul 20 00:04:13 2004
"""

__CHEETAH_genTime__ = 'Tue Jul 20 00:13:27 2004'
__CHEETAH_src__ = 'projectlist.tmpl'
__CHEETAH_version__ = '0.9.15'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFS=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class projectlist(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''<html>
    <head>
        <title>Projects</title>
    </head>
    <body>
        <h1>Projects:</h1>
        <hr/>
''')
        for project in VFS(SL + [globals(), __builtin__],"projects",True):
            write('            <p><a href="index?view=projectdetail&project=')
            write(filter(VFN(project,"id",True), rawExpr='$project.id')) # from line 9, col 58.
            write('">')
            write(filter(VFS(SL + [globals(), __builtin__],"format",False)(VFN(project,"name",True)), rawExpr='$format($project.name)')) # from line 9, col 71.
            write(' (')
            write(filter(VFS(SL + [globals(), __builtin__],"format",False)(VFN(project,"version",True)), rawExpr='$format($project.version)')) # from line 9, col 95.
            write(')</a></p>\n')
        write('    </body>\n</html>\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_projectlist= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    projectlist().runAsMainProgram()

