#!/usr/bin/env python
# 
# Copyright 2002, 2003 Zuza Software Foundation
# 
# This file is part of translate.
#
# translate is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""script that converts a set of .po files to a set of .dtd and .properties files
either done using a template or just using the .po file"""

from translate.convert import po2dtd
from translate.convert import po2prop
from translate.storage import dtd
from translate.storage import po
from translate.misc import quote
from translate import __version__

if __name__ == '__main__':
  # handle command line options
  from translate.convert import convert
  inputformat = "po"
  outputformats = {"dtd": po2dtd.convertdtd, "properties": po2prop.convertprop}
  parser = convert.ConvertOptionParserExt(convert.defaultrecursion, inputformat, outputformats, usetemplates=True)
  (options, args) = parser.parse_args()
  try:
    parser.runconversion(options)
  except convert.optparse.OptParseError, message:
    parser.error(message)

