#!/usr/bin/env python

import wx
import os
from translate.misc import xmlwrapper

availablelanguages = {'en-US': 'English (US)', 'af': 'Afrikaans', 'ns': 'Sipedi', 'zu': 'Zulu'}

class oosetupfile(xmlwrapper.XMLWrapper):
  def __init__(self, setupfile):
    self.setupfile = setupfile
    if not os.path.isfile(self.setupfile):
      raise ValueError("Could not find setup file: %s" % self.setupfile)
    contents = open(self.setupfile, 'r').read()
    root = xmlwrapper.BuildTree(contents)
    xmlwrapper.XMLWrapper.__init__(self, root)

  def getcurrentlanguage(self):
    for node in self.getchildren("node"):
      if node.getattr("name") == "L10N":
        for prop in self.getchildren("prop"):
          if prop.getattr("name") == "ooLocale":
            language = prop.getplaintext().strip()
            return language
    raise ValueError("Error finding language node")

  def setcurrentlanguage(self, language):
    for node in self.getchildren("node"):
      if node.getattr("name") == "L10N":
        for prop in self.getchildren("prop"):
          if prop.getattr("name") == "ooLocale":
            value = prop.getchild("value")
            value.obj.text = language
            return
    raise ValueError("Error finding language node")

  def savetofile(self, filename=None):
    if filename is None:
      filename = self.setupfile
    oonamespace = {'http://openoffice.org/2001/registry': 'oor', 'http://www.w3.org/2001/XMLSchema': 'xs'}
    self.obj.attrib['xmlns:xs'] = "http://www.w3.org/2001/XMLSchema"
    xmlwrapper.ElementTree.fixtag = xmlwrapper.makefixtagproc(oonamespace)
    self.write(open(filename, 'w'))

class ooconfigurator:
  """manages an open office configuration in a given directory"""
  def __init__(self, installdir):
    self.installdir = installdir
    adminsetupfilename = os.path.join(self.installdir, 'share', 'registry', 'data', 'org', 'openoffice', 'Setup.xcu')
    usersetupfilename = os.path.join(self.installdir, 'user', 'registry', 'data', 'org', 'openoffice', 'Setup.xcu')
    self.adminsetupfile = oosetupfile(adminsetupfilename)
    self.usersetupfile = oosetupfile(usersetupfilename)

  def getadminlanguage(self):
    """gets the language set for this user"""
    return self.adminsetupfile.getcurrentlanguage()

  def getuserlanguage(self):
    """gets the language set for this user"""
    try:
      return self.usersetupfile.getcurrentlanguage()
    except ValueError:
      return self.getadminlanguage()

  def setofficelang(self, newisocode, admin=False, force=False):
    """sets the language using the setofficelang program"""
    programdir = os.path.join(self.installdir, "program")
    cmdline = []
    for ext in 'bin', 'exe':
      binname = os.path.join(programdir, 'setofficelang' + os.path.extsep + ext)
      if os.path.exists(binname):
        cmdline.append(binname)
        break
    if not cmdline:
      raise IOError("Could not find setofficelang executable in %s" % programdir)
    if admin: cmdline.append("-a")
    if force: cmdline.append("-f")
    cmdline.append(newisocode)
    wx.BeginBusyCursor()
    retcode = os.system(" ".join(cmdline))
    wx.EndBusyCursor()
    if retcode == 1:
      raise ValueError("The language is not supported by this office installation")
    elif retcode == 2:
      raise ValueError("Invalid arguments")
    elif retcode == 3:
      raise ValueError("An internal error occurred")
    elif retcode:
      raise ValueError("Unknown error: %d" % retcode)

  def setuserlanguage(self, newisocode):
    """sets the language for the user"""
    self.setofficelang(newisocode)

  def setadminlanguage(self, newisocode):
    """sets the language for the user"""
    self.setofficelang(newisocode, admin=True)

class LanguageSelectionWindow(wx.Frame):
  """Window for selecting language"""
  def __init__(self, parent, id, title):
    wx.Frame.__init__(self, parent, id, title)
    self.config = ooconfigurator('.')
    self.panel = wx.Panel(self, wx.ID_ANY)
    self.languagelabel = wx.StaticText(self.panel, wx.ID_ANY, "Select language:")
    self.languages = availablelanguages
    self.languagenames = self.languages.values()
    self.languagenames.sort()
    self.languagelist = wx.ListBox(self.panel, wx.ID_ANY, choices=self.languagenames)

    self.adminlabel = wx.StaticText(self.panel, wx.ID_ANY, "Set defaults:")
    self.adminchoice = wx.CheckBox(self.panel, wx.ID_ANY, "")
    wx.EVT_CHECKBOX(self, self.adminchoice.GetId(), self.OnSetAdmin)
    
    self.showcurrentlanguage()

    self.optionssizer = wx.FlexGridSizer(0, 2, 0, 0)
    self.optionssizer.Add(self.languagelabel, 0, wx.ALIGN_LEFT|wx.ALIGN_TOP|wx.ALL, 5)
    self.optionssizer.Add(self.languagelist, 0, wx.ALIGN_LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5)
    self.optionssizer.Add(self.adminlabel, 1, wx.ALIGN_LEFT|wx.ALIGN_TOP|wx.ALL, 5)
    self.optionssizer.Add(self.adminchoice, 1, wx.ALIGN_LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5)

    self.applybutton = wx.Button(self.panel, wx.ID_ANY, "Apply Changes")
    self.applybutton.SetDefault()
    wx.EVT_BUTTON(self, self.applybutton.GetId(), self.OnApply)
    self.cancelbutton = wx.Button(self.panel, wx.ID_ANY, "Cancel")
    wx.EVT_BUTTON(self, self.cancelbutton.GetId(), self.OnCancel)
    self.buttonsizer = wx.BoxSizer(wx.HORIZONTAL)
    self.buttonsizer.Add(self.applybutton)
    self.buttonsizer.Add(self.cancelbutton)

    self.sizer = wx.BoxSizer(wx.VERTICAL)
    self.sizer.Add(self.optionssizer)
    self.sizer.Add(self.buttonsizer)
    self.panel.SetAutoLayout(1)
    self.panel.SetSizer(self.sizer)
    self.Show(1)

  def getlanguage(self):
    if self.adminchoice.GetValue():
      return self.config.getadminlanguage()
    else:
      return self.config.getuserlanguage()

  def setlanguage(self, newisocode):
    if self.adminchoice.GetValue():
      self.config.setadminlanguage(newisocode)
    else:
      self.config.setuserlanguage(newisocode)
    wx.MessageBox("Setting language successful", "ooswitchlang", wx.OK, self)

  def showcurrentlanguage(self):
    currentisocode = self.getlanguage()
    currentlanguagename = self.languages.get(currentisocode, None)
    if currentlanguagename in self.languagenames:
      self.languagelist.Select(self.languagenames.index(currentlanguagename))

  def OnSetAdmin(self, event):
    """Sets whether or not we are using admin choices..."""
    self.showcurrentlanguage()
    event.Skip()

  def OnApply(self, event):
    """Apply the changes and quit"""
    currentlanguagename = self.languagelist.GetStringSelection()
    if currentlanguagename:
      currentisocode = None
      for isocode, languagename in self.languages.iteritems():
        if languagename == currentlanguagename:
          currentisocode = isocode
          break
      if currentisocode is None:
        wx.MessageBox("Error finding language code", "Error", wx.ICON_ERROR, self)
      else:
        self.setlanguage(currentisocode)
        self.Close(1)
    else:
      wx.MessageBox("First select a language (Cancel to quit)", "Error", wx.ICON_ERROR, self)

  def OnCancel(self, event):
    """Cancel without applying changes"""
    self.Close(1)

if __name__ == '__main__':
  app = wx.PySimpleApp()
  frame = LanguageSelectionWindow(None, -1, "Choose language")
  app.MainLoop()

